apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: webhook
resources:
  - clusterrolebinding.yaml
  - config-leader-election.yaml
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - role.yaml
  - webhooks.yaml
images:
  - name: gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/webhook
    newTag: v0.29.2@sha256:fef9e5026869a6758122beec29f5ce8501be7134d50615d08effb1151f353227
